version: '3.4'

services:
  tumplate.api:
    image: tumplateapi
    build:
      context: .
      dockerfile: TumPLATE.Api/Dockerfile
    environment:
      - ASPNETCORE_ConnectionStrings__AzureAppConfiguration=${AzureAppConfiguration}
      - ASPNETCORE_ConnectionStrings__DbConnectionString=${DbConnectionString}
    ports:
      - "7357:80"
    depends_on:
      - mssql_server

  mssql_server:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Passw0rd!
      - ACCEPT_EULA=Y