version: "3.9"
services:
  webapi:
    build:
      context: /TumPLATE.Api/
      dockerfile: Dockerfile
    ports:
      - "5180:80"
    environment:
      - ASPNETCORE_ConnectionStrings__AzureAppConfiguration=Endpoint=
      - ASPNETCORE_ConnectionStrings__DbConnectionString=Server=mssql_server;Database=MyDB;User Id=SA;Password=Passw0rd!;TrustServerCertificate=true
    depends_on:
      - mssql_server
  
  mssql_server:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Passw0rd!
      - ACCEPT_EULA=Y