// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TumPLATE.Infrastructure.Persistence;

#nullable disable

namespace TumPLATE.Infrastructure.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20221206212934_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TumPLATE.Domain.Tree.Fruit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<int?>("TreeStateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TreeStateId");

                    b.ToTable("Fruit");
                });

            modelBuilder.Entity("TumPLATE.Domain.Tree.TreeState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastFruitAddingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trees");
                });

            modelBuilder.Entity("TumPLATE.Domain.Tree.Fruit", b =>
                {
                    b.HasOne("TumPLATE.Domain.Tree.TreeState", null)
                        .WithMany("Fruits")
                        .HasForeignKey("TreeStateId");
                });

            modelBuilder.Entity("TumPLATE.Domain.Tree.TreeState", b =>
                {
                    b.Navigation("Fruits");
                });
#pragma warning restore 612, 618
        }
    }
}
